# Generated by Django 5.2.8 on 2025-11-22 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('explicit_url', models.CharField(blank=True, help_text='Прямой URL, например /about/', max_length=500)),
                ('named_url', models.CharField(blank=True, help_text='Имя url (reverse name), например app:detail', max_length=200)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('menu_name', 'title', 'parent')},
            },
        ),
    ]
